### ISSUE TITLE
Is the number of news returned hard-capped at 300?

### ISSUE THREAD

**Issue by YukunYangNPF** [Iceloof/GoogleNews#61] opened 2021-04-12 16:51 UTC
I did a monthly search and the number of returned results never surpasses 300. Is that a hard limit that cannot find a workaround?

**Comment by HurinHu** [comment] 2021-04-15 21:35
That is what you search on the google news, if it only return 300, that means google only return that number of data.

**Comment by HurinHu** [comment] 2021-05-09 04:15
The issue is fixed in the latest version

**Closed by HurinHu** 2021-05-09 04:15 UTC
